# params.yaml
model:
  name: "bert-base-chinese"
  num_labels: 5

training:
  epochs: 3
  batch_size: 8
  learning_rate: 2e-5
  max_length: 128

data:
  path: "data/raw/annotations.json"
  max_length: 2048